namespace ToyRobotSimulator.Commands
{
    /// <summary>
    ///     Represents the token information generated by CommandInterpreter.Lexer.
    /// </summary>
    public class LexerResult
    {
        /// <summary>
        ///     Gets and sets the command token.
        /// </summary>
        public string CommandToken { get; set; }

        /// <summary>
        ///     Gets and sets the collection of parameter tokens.
        /// </summary>
        public string[] ParameterTokens { get; set; }
    }
}
